version: '3'

services:

  scanner:
    restart: always
    build:
      context: scanner/clamav/docker
      dockerfile: Dockerfile
    ports:
      - 3310:3310
    expose:
      - 3310
    networks:
      virus-scanner-network:
        aliases:
          - virus-scanner-network

  api:
    restart: always
    build:
      context: nodejs-rest-client/
      dockerfile: Dockerfile
    depends_on:
      - scanner
    ports:
      - 1337:1337
    expose:
      - 1337
    env_file:
      - env/api.env
    networks:
      virus-scanner-network:
        aliases:
          - virus-scanner-network

networks:

  virus-scanner-network:
    driver: bridge
